# Generated by Django 3.2.3 on 2023-07-10 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInterfaceTheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('active', models.BooleanField()),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('title_visible', models.BooleanField()),
                ('logo', models.CharField(blank=True, max_length=100, null=True)),
                ('logo_visible', models.BooleanField()),
                ('css_header_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('title_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_header_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_rounded_corners', models.BooleanField()),
                ('css_generic_link_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_generic_link_hover_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_background5185', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_backgroundd677', models.CharField(blank=True, max_length=10, null=True)),
                ('css_save_button_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_backgroucea0', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_backgrou6352', models.CharField(blank=True, max_length=10, null=True)),
                ('css_delete_button_text_color', models.CharField(blank=True, max_length=10, null=True)),
                ('list_filter_dropdown', models.BooleanField()),
                ('related_modal_active', models.BooleanField()),
                ('related_modal_background_color', models.CharField(blank=True, max_length=10, null=True)),
                ('related_modal_rounded_corners', models.BooleanField()),
                ('logo_color', models.CharField(blank=True, max_length=10, null=True)),
                ('recent_actions_visible', models.BooleanField()),
                ('favicon', models.CharField(blank=True, max_length=100, null=True)),
                ('related_modal_background_o7c6e', models.CharField(blank=True, max_length=5, null=True)),
                ('env_name', models.CharField(blank=True, max_length=50, null=True)),
                ('env_visible_in_header', models.BooleanField(blank=True, null=True)),
                ('env_color', models.CharField(blank=True, max_length=10, null=True)),
                ('env_visible_in_favicon', models.BooleanField()),
                ('related_modal_close_button8203', models.BooleanField()),
                ('language_chooser_active', models.BooleanField()),
                ('language_chooser_display', models.CharField(blank=True, max_length=10, null=True)),
                ('list_filter_sticky', models.BooleanField()),
                ('form_pagination_sticky', models.BooleanField()),
                ('form_submit_sticky', models.BooleanField()),
                ('css_module_background_selec21b', models.CharField(blank=True, max_length=10, null=True)),
                ('css_module_link_selected_color', models.CharField(blank=True, max_length=10, null=True)),
                ('logo_max_height', models.IntegerField()),
                ('logo_max_width', models.IntegerField()),
                ('foldable_apps', models.BooleanField()),
                ('language_chooser_control', models.CharField(blank=True, max_length=20, null=True)),
                ('list_filter_highlight', models.BooleanField()),
                ('list_filter_removal_links', models.BooleanField()),
                ('show_fieldsets_as_tabs', models.BooleanField()),
                ('show_inlines_as_tabs', models.BooleanField()),
                ('css_generic_link_active_color', models.CharField(blank=True, max_length=10, null=True)),
                ('collapsible_stacked_inlines', models.BooleanField()),
                ('collapsible_stacked_inlinea0a8', models.BooleanField()),
                ('collapsible_tabular_inlines', models.BooleanField()),
                ('collapsible_tabular_inline8750', models.BooleanField()),
            ],
            options={
                'db_table': 'admin_interface_theme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthtokenToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
            ],
            options={
                'db_table': 'authtoken_token',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatgLibro',
            fields=[
                ('id_catg', models.AutoField(primary_key=True, serialize=False)),
                ('catg_libro', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'catg_libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut_cli', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_cli', models.CharField(max_length=30)),
                ('ap_paterno_cli', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_cli', models.CharField(max_length=50)),
                ('telefono_cli', models.IntegerField()),
                ('usuario_cli', models.CharField(max_length=30)),
                ('contrasenia_cli', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id_despc', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_despc', models.CharField(max_length=30)),
                ('precio_despc', models.IntegerField()),
            ],
            options={
                'db_table': 'despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('rut_emp', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=20)),
                ('ap_paterno_emp', models.CharField(max_length=30)),
                ('correo_emp', models.CharField(max_length=40)),
                ('telefono_emp', models.IntegerField()),
                ('usuario_emp', models.CharField(max_length=15)),
                ('contrasenia_emp', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_est', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_libro', models.CharField(max_length=40)),
                ('autor_libro', models.CharField(max_length=40)),
                ('sinopsis_libro', models.CharField(blank=True, max_length=250, null=True)),
                ('precio_libro', models.IntegerField()),
                ('stock_libro', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='libros')),
            ],
            options={
                'db_table': 'libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id_compra', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_or_compra', models.DateField()),
                ('total_final_or', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orden_compra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_serv', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_serv', models.CharField(max_length=50)),
                ('dscrp_serv', models.CharField(blank=True, max_length=250, null=True)),
                ('precio_serv', models.IntegerField()),
            ],
            options={
                'db_table': 'servicio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id_tp_cli', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tp_cli', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoEmpleado',
            fields=[
                ('id_tp_emp', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tp_emp', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'tipo_empleado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tp_pago', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_tp_pago', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenDespacho',
            fields=[
                ('fecha_despc', models.DateField()),
                ('direccion_despc', models.CharField(max_length=100)),
                ('indicaciones_despc', models.CharField(blank=True, max_length=250, null=True)),
                ('id_despc', models.OneToOneField(db_column='id_despc', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.despacho')),
            ],
            options={
                'db_table': 'orden_despacho',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenLibro',
            fields=[
                ('total_detalle_libro', models.IntegerField()),
                ('cant_libro', models.IntegerField()),
                ('id_libro', models.OneToOneField(db_column='id_libro', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.libro')),
            ],
            options={
                'db_table': 'orden_libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('total_detalle_serv', models.IntegerField()),
                ('cant_serv', models.IntegerField()),
                ('fecha_serv', models.DateField(blank=True, null=True)),
                ('detalle_serv', models.CharField(blank=True, max_length=250, null=True)),
                ('confirm_serv', models.FloatField(blank=True, null=True)),
                ('id_serv', models.OneToOneField(db_column='id_serv', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='core.servicio')),
            ],
            options={
                'db_table': 'orden_servicio',
                'managed': False,
            },
        ),
    ]
